# Generated by Django 4.1 on 2022-12-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_product_slug_alter_product_product_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
            ],
        ),
    ]
