# Generated by Django 4.1 on 2022-12-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_brand_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='Name',
            new_name='name',
        ),
    ]
