# Generated by Django 4.1 on 2022-12-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_rename_name_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Tax',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='packing_cost',
            field=models.IntegerField(null=True),
        ),
    ]
